# Generated by Django 4.2.7 on 2023-11-20 13:37

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='images/profile'),
            preserve_default=False,
        ),
    ]
