# Generated by Django 4.2.7 on 2023-12-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_last_name_profile_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proffession',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
