# Generated by Django 4.2.7 on 2023-11-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugoingewa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pice',
            field=models.CharField(max_length=255),
        ),
    ]
