# Generated by Django 4.2.7 on 2023-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugoingewa', '0002_alter_event_pice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pice',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
