# Generated by Django 4.2.7 on 2023-12-25 11:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugoingewa', '0006_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='price',
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
