# Generated by Django 4.2.7 on 2023-12-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugoingewa', '0007_remove_story_price_story_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='description',
            new_name='Story',
        ),
    ]
