# Generated by Django 4.2.7 on 2023-12-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugoingewa', '0008_rename_description_story_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='readtime',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
