# Generated by Django 4.2.7 on 2023-12-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugoingewa', '0009_story_readtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='readtime',
            field=models.CharField(max_length=255),
        ),
    ]
