# Generated by Django 4.2.7 on 2023-12-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugoingewa', '0011_initiative'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Initiative',
        ),
    ]
