# Generated by Django 4.2.7 on 2023-12-31 06:18

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tugoingewa', '0014_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='category',
            field=models.CharField(default='Sustainabilility', max_length=255),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='initiative_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='initiatives/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='stories/'),
        ),
    ]
