# Generated by Django 4.2.7 on 2023-12-31 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tugoingewa', '0015_initiative_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
